# Generated by Django 5.0.2 on 2024-02-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangerapp', '0002_tag_manger_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manger',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
