# Generated by Django 5.0.2 on 2024-02-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boireapp', '0001_initial'),
        ('mangerapp', '0002_tag_manger_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boireapp.boire')),
                ('manger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mangerapp.manger')),
            ],
        ),
    ]
