# Generated by Django 5.0.2 on 2024-02-28 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boireapp', '0001_initial'),
        ('commande', '0002_remove_commande_boire_commande_boire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='boire',
        ),
        migrations.AddField(
            model_name='commande',
            name='boire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boireapp.boire'),
        ),
    ]
